- name: gathering facts 
  hosts: frontend 
  become: true 
  tasks:
  - name: printing ansible facts 
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}"
  - name: printing information from ansible facts 
    ansible.builtin.debug:
      msg:
      - "Operating system is {{ ansible_facts['os_family'] }}"
      - "Public IP address is {{ ansible_facts['all_ipv4_addresses'] }}"
      - "Host Name is {{ ansible_facts['hostname'] }}"